language: node_js
node_js: 6

install:
  - yarn

env:
  - PACKAGE=formation
  - PACKAGE=formation-validators

script:
  - cd packages/$PACKAGE
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  - yarn test -- --coverage

after_success:
  - yarn add codacy-coverage
  - $(npm bin)/codacy-coverage -v < ./coverage/lcov.info

cache:
  yarn: true
  directories:
    - node_modules
