language: node_js
node_js: 6

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

env:
  - PACKAGE=formation
  - PACKAGE=formation-validators

script:
  - cd packages/$PACKAGE
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  - yarn test -- --coverage

after_success:
  - yarn add codacy-coverage
  - $(npm bin)/codacy-coverage -v < ./coverage/lcov.info

cache:
  yarn: true
  directories:
    - node_modules
