language: node_js
node_js: 6

install:
  - npm install

script:
  - npm run test -- --coverage

after_success:
  - npm install codacy-coverage
  - $(npm bin)/codacy-coverage -v < ./coverage/lcov.info

cache:
  directories:
    - node_modules
