language: node_js
node_js: 8

install:
  - npm install --ignore-scripts
  - npm run prepare

env:
  - PACKAGE=formation
  - PACKAGE=formation-validators

script:
  - cd packages/$PACKAGE
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  - npm test -- --coverage

after_success:
  - npm install codacy-coverage
  - $(npm bin)/codacy-coverage -v < ./coverage/lcov.info

cache:
  directories:
    - node_modules
